version: "3.9"

services:
  mongo:
    image: mongo:8
    container_name: mongo
    restart: always
    ports:
      - "27117:27017"
    volumes:
      - mongo-data:/data/db
    networks:
      - app-network

  angular-app:
    build:
      context: .
      dockerfile: front/Dockerfile
    container_name: angular-app
    ports:
      - "3008:80"
    restart: unless-stopped
    networks:
      - app-network

  nest-api:
    build:
      context: .
      dockerfile: server/Dockerfile
    container_name: nest-api
    restart: always
    ports:
      - "3007:3007"
    env_file:
      - server/.env
      - server/.env.local
    depends_on:
      - mongo
    environment:
      NODE_ENV: production
    networks:
      - app-network

  nginx:
    image: nginx:1.25
    container_name: nginx
    restart: unless-stopped
    ports:
      - "8080:80"
    volumes:
      - ./conf/nginx/jira-front.dev.conf:/etc/nginx/conf.d/jira-front.conf:ro
      - ./conf/nginx/jira-api.dev.conf:/etc/nginx/conf.d/jira-api.conf:ro
    depends_on:
      - angular-app
      - nest-api
    networks:
      - app-network

volumes:
  mongo-data:

networks:
  app-network:
    driver: bridge