version: "3"
services:
  #nest-api:
  #  container_name: nest-api
  #  build:
  #    context: .
  #    dockerfile: Dockerfile
  #  ports:
  #    - 3000:3000
    #depends_on:
    #  - postgres

  jira-api-server:
    build:
      context: .
      dockerfile: ./server/Dockerfile
    ports:
      - "3007:3007"
    #command: npm start
    #  env_file:
    #    - .env

  jira-api-front:
    build:
      context: .
      dockerfile: ./front/Dockerfile
    ports:
      - "3008:3008"
