server {

   listen 80;

   server_name  jira-front.dev;

   access_log    /var/log/nginx/jira-front.access.log;
   error_log     /var/log/nginx/jira-front.error.log;

   root /var/www/jira-api/front/dist/jira-front;

   #ssl_session_timeout 5m;
   #ssl_protocols SSLv3 TLSv1 TLSv1.1 TLSv1.2;
   #ssl_ciphers "HIGH:!aNULL:!MD5 or HIGH:!aNULL:!MD5:!3DES";
   #ssl_prefer_server_ciphers on;

   client_max_body_size 512m;
   proxy_read_timeout 300;

   location ~* .(js|gz|css|gif|png)$ {
        root /var/www/jira-api/front/dist/jira-front;

        expires 14d;
        try_files $uri @handler;
   }

   location / {
        index index.html;
        root /var/www/jira-api/front/dist/jira-front;
        
        try_files $uri $uri/ @handler;
   }

   location @handler {
      index index.html;
      root /var/www/jira-api/front/dist/jira-front;

      rewrite / /index.html;
   }

}
